//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#include "EleniHealth_Firmware_Native.h"

// clang-format off

static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_EleniHealth_Firmware_Native_EleniHealth_Firmware_Native_RMTHelper::NativeGetRegister___STATIC__U4__U4,
    Library_EleniHealth_Firmware_Native_EleniHealth_Firmware_Native_RMTHelper::NativeSetRegisterOrOp___STATIC__VOID__U4__U4,
    Library_EleniHealth_Firmware_Native_EleniHealth_Firmware_Native_RMTHelper::NativeSetRegisterAndOp___STATIC__VOID__U4__U4,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_EleniHealth_Firmware_Native =
{
    "EleniHealth.Firmware.Native",
    0xAF84D2F2,
    method_lookup,
    { 1, 0, 0, 0 }
};

// clang-format on
